# -*- mode: ruby -*-
# vi: set ft=ruby:

VAGRANTFILE_API_VERSION = "2"

num_machines = 4

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end
    config.vm.network "private_network", type: "dhcp"
    config.ssh.forward_agent = true
    num_machines.times do |i|
        hostname = "v-trusty-%d" % [(i+1)]
        config.vm.define :"#{hostname}" do |box|
            box.vm.hostname = hostname
            box.vm.provision "shell", path: "setup_ubuntu"
        end
    end
end
